version: '3'

services:
  app:
    build: 
      context: .
    ports:
      - "8080:8080"
    depends_on:
        db:
            condition: service_healthy
    networks:
      - catering

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: catering_management
      MYSQL_ROOT_PASSWORD: 1234
      # MYSQL_USER: mysql
      # MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    networks:
      - catering
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 20s
        retries: 10
networks:
  catering:
    driver: bridge
