version: '3'

services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DATABASE_URL: "root:1234@tcp(db:3306)/catering_management"
      JWT_SECRET: "your_jwt_secret"

  db:
    image: 'mysql'
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: catering_management
    ports:
      - "3306:3306"
 